### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.

### ISSUE THREAD

**Issue by kimsw61** [Satak/webrequest-action#23]
i'm using v1.2.4 now.

but every action running, appear on warning

"Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: satak/webrequest-action@v1.2.4"

please upgrade node please

**Comment by vkodocha** [comment]
Just made a pr with an fix: #27

**Comment by Satak** [comment]
updated
