### ISSUE TITLE
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: Satak/webrequest-action@v1.2.3.

### ISSUE THREAD

**Issue by Phasor** [Satak/webrequest-action#26]
I get this warning when trying to use this action.

Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: Satak/webrequest-action@v1.2.3.

**Comment by Satak** [comment]
released 1.4.0 version that has axios and actions/core updated to latest. Should fix deprecation messages.
