### ISSUE TITLE
Bug: Fail to load

### ISSUE THREAD

**Issue by HiptJo** [Satak/webrequest-action#28]
When running the action containing satak/webrequest-action the following error is raised during the _Setup Job_ section:

```
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node[12](https://github.com/HiptmairIT/wasser/actions/runs/5287733509/jobs/9568584229#step:1:12)' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load satak/webrequest-action/master/action.yml
```

**Comment by Satak** [comment]
I can’t reproduce. Can you show the action? Mine test works ok here: https://github.com/Satak/webrequest-action/blob/master/.github/workflows/test.yml

**Comment by HiptJo** [comment]
I was able to gather additional information on this topic.
It seems to be connected to self-hosted github actions runners and other action templates are affected as well.
For whatever reason node16 is no longer supported after updating docker. Others complain about this issue as well when installing node16 during the action runs.

In the meantime i created a fork of your repository and just changed the node version to v12. This fixed the issue for me for now.
