### ISSUE TITLE
Can't parse web request result

### ISSUE THREAD

**Issue by qcloop** [Satak/webrequest-action#8]
Given this snippet

  - uses: satak/webrequest-action@master
        id: generate_report
        with:
          url: http://myurl.com/query=myparam
          method: POST
          headers: '{"Content-Type" : "application/json"}'
      - run: |
         echo report result: ${{ steps.generate_report.outputs.output.data }}

Does not echo the data, even though I see this 

```
Run satak/webrequest-action@master
2
  with:
3
    url: http://myurl.com/query=myparam
4
    method: POST
5
    headers: {"Content-Type" : "application/json"}
6
{
7
  "url": "http://myurl.com/query=myparam",
8
  "method": "post",
9
  "payload": null,
10
  "time": "19:56:19 GMT+0000 (Coordinated Universal Time)",
11
  "statusCode": 200,
12
  "data": {
.....
```

**Comment by Satak** [comment]
will check it

**Comment by Satak** [comment]
Have you tried parsing the output json string with powershell like this:

```
     - name: get-request output
        shell: pwsh
        run: |
          $output = '${{ steps.generate_report.outputs.output }}' | ConvertFrom-Json
          $output.data
```

**Comment by qcloop** [comment]
I don't use windows, but perhaps, will look into linux alternatives

**Comment by Satak** [comment]
> I don't use windows, but perhaps, will look into linux alternatives

You can use pwsh shell in linux also. It's cross platform. I'm pretty sure that the problem is in your parsing. JSON is basically a string that you need to first parse out.

**Comment by qcloop** [comment]
Thanks, I used a different approach and it works.
